# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "lastname" varchar not null,
  "age" int not null,
  "email" varchar not null,
  "passport" varchar not null
);

create table "contracts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "personId" bigint not null,
  "beginDate" varchar not null,
  "endDate" varchar not null
);

# --- !Downs
#drop table "people" if exists;
#drop table "contracts" if exists;