# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "lastname" varchar not null,
  "age" int not null,
  "email" varchar not null,
  "passport" varchar not null,
  "removed" boolean not null
);

create table "properties" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "code" varchar not null,
  "line1" varchar not null,
  "line2" varchar,
  "line3" varchar,
  "zipcode" varchar not null,
  "rooms" int not null,
  "removed" boolean not null
);

create table "contracts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "personId" bigint not null,
  "propertyId" bigint not null,
  "beginDate" varchar not null,
  "endDate" varchar not null,
  "notes" varchar,
  "numberAdvances" int not null,
  "numberDeposits" int not null,
  "rentAmount" double not null,
  "depositAmount" double not null,
  "removed" boolean not null
);

create table "payments" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "personId" bigint not null,
  "contractId" bigint not null,
  "date" varchar not null,
  "amount" varchar,
  "type" int not null,
  "status" int not null,
  "removed" boolean not null
);



# --- !Downs
#drop table "people" if exists;
#drop table "properties" if exists;
#drop table "contracts" if exists;